version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - redis
    networks:
      - laravel
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8977:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - laravel
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - laravel

networks:
  laravel:
